on:
  push:
    branches: [main, master]

name: atualizar_pagina_do_curso

jobs:
  render-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Execute Script
        run: Rscript "inst/atualizar_pagina.R"

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.Rmd
          git add README.md
          git add _config.yml
          git commit -m "Atualizando página do curso" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
