on: workflow_dispatch

name: mover actions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: copy file and Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mv --verbose inst/atualizar_pagina_do_curso.yaml .github/workflows/atualizar_pagina_do_curso.yaml
          git add .github/workflows/atualizar_pagina_do_curso.yaml
          git commit -m "Movendo o GHA" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
